require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*
    - node_modules/**/*

Rails:
  Enabled: true



Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - spec/**/*
    - db/migrate/**/*

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_special
  Exclude:
    - db/migrate/**/*

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_special

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 120
  IgnoredPatterns:
    - ^\W*\#

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
  SupportedStyles:
    - indented
    - indented_relative_to_receiver

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/RescueEnsureAlignment:
  Enabled: false



Metrics/AbcSize:
  Exclude:
    - db/migrate/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - lib/tasks/**/*.rake
    - config/routes.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*

Metrics/ModuleLength:
  Exclude:
    - spec/**/*



Style/AccessModifierDeclarations:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - app/controllers/**/*

Style/Documentation:
  Exclude:
    - db/migrate/**/*
    - spec/**/*

Style/DocumentationMethod:
  Enabled: true
  RequireForNonPublicMethods: true
  Exclude:
    - db/migrate/**/*
    - bin/**/*
    - spec/**/*

Style/DoubleNegation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma



Rails/Blank:
  UnlessPresent: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments
